; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32c3]
platform = https://github.com/pioarduino/platform-espressif32/archive/refs/tags/55.03.33.zip
board = seeed_xiao_esp32c3
framework = arduino
; board_build.arduino.upstream_packages = no

; platform_packages =
;     framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.3.3

lib_deps =
    knolleary/PubSubClient
    ; https://github.com/bluerobotics/BlueRobotics_MS5837_Library.git#1.1.1

upload_protocol = espota
upload_port = 192.168.137.91

; 192.168.8.79
